version: "2.1"

services:

  scylla-node1:
    image: qxip/scylladb
    restart: always
    networks:
      web:
        ipv4_address: 10.10.10.1
    environment:
      - DC1=DC1
      - SEEDS=10.10.10.1,10.10.10.2,10.10.10.3
      - CQLSH_HOST=10.10.10.1
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

  scylla-node2:
    image: qxip/scylladb
    restart: always
    networks:
      web:
        ipv4_address: 10.10.10.2
    environment:
      - DC1=DC1
      - SEEDS=10.10.10.1,10.10.10.2,10.10.10.3
      - CQLSH_HOST=10.10.10.2
    depends_on:
      scylla-node1:
        condition: service_healthy

  scylla-node3:
    image: qxip/scylladb
    restart: always
    networks:
      web:
        ipv4_address: 10.10.10.3
    environment:
      - DC1=DC1
      - SEEDS=10.10.10.1,10.10.10.2,10.10.10.3
      - CQLSH_HOST=10.10.10.3
    depends_on:
      scylla-node1:
        condition: service_healthy

  manticore-node1:
    image: manticoresearch/manticore
    restart: always
    expose:
    - 9306
    - 9312
    networks:
      web:
        ipv4_address: 10.10.10.50
    environment:
      - DC1=DC1
    depends_on:
      scylla-node1:
        condition: service_healthy

networks:
  web:
    driver: bridge
    ipam:
     config:
       - subnet: 10.10.10.0/16
